sudo: false
dist: trusty

language: python

jobs:
  include:
    - python: "2.7"
      script: python -m unittest discover tests/python2/
    - python: "3.4"
      script: python -m unittest discover tests/python3/
    - python: "3.5"
      script: python -m unittest discover tests/python3/
    - python: "3.6"
      script: python -m unittest discover tests/python3/
    - python: "3.7"
      dist: xenial
      sudo: true
      script: python -m unittest discover tests/python3/
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: norcuni
        password:
          secure: q9UrBosh5vLnIaSJC+Df4fkjQ01roiTCAYPvK2wLUM63fXng6KoUKJ389iRKZMdVtVR80iF2WHlRzYXKB5uBfqLaG5XaPvXC1kzRcVLcF7Sx9RPQydxGRpc/bvtCppL8CglbXh9tQzzDlH4A0xPMXIxa03mH8FSVx6TvtpB8guBUYkmJOybOg+2KWBCFBBFDJ4mFsK7lKbPEqShaAE8VmPTdgpSps5yXOumOf+6frXROf1qd6DkZXc+0cAu5DldpoulRWjs3y0RZhIPA2BtiPr2UOIma2qyAQA64lcX8OpLu6FG4QDdEwVrAwU6QAJZ7K7/mT7LdOR3tkEelxHi5SVHg+X6ameZI1rKC/NztQsm6ZuaMnvC4nUZBpKZdV89iyPIF1v3WdZgPy6tyDXj1rq6pCxpLDW/yZDCc53mxkE9xw6p6ScdpQqkFyMj1s5hJB/1Of6L+UE/MMnCoxWw1HTCLuUq5UEK5w/HGnH4xVaB4/3HCD6KoveGqFirkRPcjtlAjUxjzxdRbBXIXUxVfpts4flHXc3DhW0+lvNUGvjzurqx9C6zxEKEBulbAEsghB4qVfeiYIl8xrXqRxRAFpiFiCCmzOjjSAvlQ+R4qfIpSr1HI9slb+jl99PMTkXhC1SucMXIYVjYMjUk04IdB35ihJlKAZ/tLBU8y8zeuNJI=
        if: type = push AND branch = master AND tag IS present
